# Generated by Django 4.2.2 on 2023-08-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
