# Generated by Django 4.2.2 on 2023-09-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_phone_number_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('-', 'Неопределен')], max_length=30, null=True, verbose_name='Гендер'),
        ),
    ]
