# Generated by Django 4.2.2 on 2023-09-15 08:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_experience_alter_profile_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Высшее образование/средне-специальное образование/курсы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Ж', 'Женский'), ('М', 'Мужской'), ('-', 'Неопределен')], max_length=30, null=True, verbose_name='Гендер'),
        ),
    ]
