# Generated by Django 4.2.2 on 2023-09-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_education_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Соцсети'),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Высшее/средне-специальное образование/курсы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='accounts.profile', verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('-', 'Неопределен'), ('Ж', 'Женский'), ('М', 'Мужской')], max_length=30, null=True, verbose_name='Гендер'),
        ),
    ]
