# Generated by Django 4.2.2 on 2023-09-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_profile_photo_alter_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Ж', 'Женский'), ('М', 'Мужской'), ('-', 'Неопределен')], max_length=30, null=True, verbose_name='Гендер'),
        ),
    ]
