# Generated by Django 4.2.2 on 2023-10-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('-', 'Неопределен')], max_length=30, null=True, verbose_name='Гендер'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField()),
                ('sended', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sended'],
                'indexes': [models.Index(fields=['-sended'], name='accounts_me_sended_bf6edb_idx')],
            },
        ),
    ]
