# Generated by Django 4.2.2 on 2023-08-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(choices=[('+', 'Завершено'), ('+/-', 'В процессе'), ('-', 'Не завершено')], default='-', max_length=30, verbose_name='Завершенность'),
        ),
    ]
