# Generated by Django 4.2.2 on 2023-09-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_status_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(choices=[('+/-', 'В процессе'), ('-', 'Не завершено'), ('+', 'Завершено')], default='-', max_length=30, verbose_name='Завершенность'),
        ),
    ]
