# Generated by Django 4.2.2 on 2023-09-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_managers_alter_status_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(choices=[('+/-', 'В процессе'), ('+', 'Завершено'), ('-', 'Не завершено')], default='-', max_length=30, verbose_name='Завершенность'),
        ),
    ]
