# Generated by Django 4.2.2 on 2023-09-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_status_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(choices=[('+/-', 'В процессе'), ('+', 'Завершено'), ('-', 'Не завершено')], default='-', max_length=30, verbose_name='Завершенность'),
        ),
    ]
